# Generated by Django 3.1.3 on 2020-11-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('key', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IPLSeason',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('season', models.IntegerField(default=2020)),
            ],
            options={
                'ordering': ['season'],
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_no', models.AutoField(primary_key=True, serialize=False)),
                ('team_one_txt', models.CharField(default='', max_length=10)),
                ('team_two_txt', models.CharField(default='', max_length=10)),
                ('toss_txt', models.CharField(default='', max_length=10)),
                ('match_won_txt', models.CharField(default='', max_length=10)),
                ('elected', models.CharField(choices=[('B', 'BAT'), ('F', 'FIELD')], max_length=1)),
                ('first_inning_score', models.IntegerField()),
                ('first_inning_over', models.FloatField()),
                ('second_inning_score', models.IntegerField()),
                ('second_inning_over', models.FloatField()),
            ],
        ),
    ]
