# Generated by Django 3.1.3 on 2020-11-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20201127_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplseason',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
