# Generated by Django 3.1.3 on 2020-11-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('team_color', models.CharField(default='white', max_length=30)),
                ('total_matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('nrr', models.FloatField(default=0.0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.iplseason')),
            ],
            options={
                'ordering': ['-points', '-nrr'],
                'unique_together': {('team_name', 'year')},
            },
        ),
    ]
