# Generated by Django 3.1.3 on 2020-11-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='India', max_length=10)),
                ('team_name', models.CharField(default='', max_length=30)),
                ('year', models.IntegerField(default=2020)),
                ('team', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
